# Configuration for running isodatetime tests on Travis CI
# See https://travis-ci.org/ for more info.

---
language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
env:
  - RUN_COVERAGE=false
  - RUN_COVERAGE=true

matrix:
  fast_finish: true
  exclude:
    - python: 3.4
      env:  RUN_COVERAGE=false
    - python: 3.5
      env:  RUN_COVERAGE=false
    - python: 3.6
      env: RUN_COVERAGE=false
    - python: 3.7-dev
      env: RUN_COVERAGE=true

before_install:
  # Tox with Travis environment support
  - pip install setuptools tox-travis
  # Coverage dependencies
  - pip install coverage pytest-cov
  # Code style dependencies
  - pip install pycodestyle
before_script:
  - pycodestyle -v isodatetime
script:
  - |
    export COVERAGE_PROCESS_START="${TRAVIS_BUILD_DIR}/.coveragerc"
    tox
after_success:
  - coverage xml --ignore-errors
  # Report metrics, such as coverage
  - '"${RUN_COVERAGE:-false}" && bash <(curl -s https://codecov.io/bash)'
